# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/img')),
            ],
        ),
    ]
